theme: jekyll-theme-slate

# Name of website
title: Reopen Evansville Task Force

# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "reopenevansville@evansville.in.gov"

#Turn off Github shout outs
github:
  is_project_page: false
